[project]
name = "dzhf"
version = "0.1.0"
description = "Uso de dataciones UPb y datos de LuHf de PanamÃ¡"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "marimo>=0.18.3",
    "numpy>=2.2.6",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "plotly>=6.5.0",
    "quak>=0.3.3",
]
